name: go

on:
  push:
    tags:
      - '*'

jobs:
  defaults:
    run:
      shell: bash
  permissions:
    actions: read
    contents: read
    security-events: read
  main:
    runs-on: ubuntu-latest
    steps:
      - run: |
          ESCAPED_MODULE=$(echo $GITHUB_REPOSITORY | tr '[:upper:]' '[:lower:]')
          curl https://proxy.golang.org/github.com/$ESCAPED_MODULE/@v/$GITHUB_REF_NAME.info
